### ISSUE TITLE
OTA Update ESP8266

### ISSUE THREAD

**Issue by glynhudson** [openenergymonitor/EmonESP#1]
OTA updating of ESP8266 firmware and ATmega328 (connected via serial) is highly desirable. Here are a collection of examples covering ESP8266 firmware update. AVR pass-through update will be explored in another issue. 
# OTA Update to ESP8266
## Pulling update from a web server
- Workflow to setup automatic build and deploy using Platformio, Git, TravisCI and a PHP script. [Blog Post](http://blog.squix.org/2016/06/esp8266-continuous-delivery-pipeline-push-to-production.html) | [Example Project Repo](https://github.com/squix78/esp8266-ci-ota) 
  ![image2](http://i2.wp.com/blog.squix.org/wp-content/uploads/2016/06/drawit-diagram.png)
## Via web interface
- Example uploading .bin via web server. [Example](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266HTTPUpdateServer/examples) | [Documentation](http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html#web-browser)

![image](http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota-web-browser-form.png)

---

Maybe we could combine both: Updating pulling from a cloud server triggered by the user hitting update in a web interface with option to upload .bin if contact with the server is not possible or custom firmware is required.

**Comment by nagansurerd** [comment]
can I upload program on esp32 through cloud
