### ISSUE TITLE
Prefer radio button rather than check box when selecting network

### ISSUE THREAD

**Issue by minida28** [openenergymonitor/EmonESP#22]
I setup a wifi repeater at home and the broadcasted SSID from both routers (same SSSID) are showed up on emonESP network selection screen.

As shown in the below screenshot, I can select both SSIDs. Not sure why, maybe it is because both SSID are identical.

Not a big deal, but it would be better if the UI implements radio button rather than check box, so only one network that can be selected at a time.

![image](https://cloud.githubusercontent.com/assets/3026584/26274793/4cf66d48-3d7c-11e7-991b-babc868519c9.png)

**Comment by glynhudson** [comment]
Good idea!

**Comment by glynhudson** [comment]
done 👍

**Comment by minida28** [comment]
Hi @glynhudson 

I've re-tested it, the button type has changed to radio.
But the strange thing is I can still select multiple networks!

![image](https://cloud.githubusercontent.com/assets/3026584/26275294/50f5a20a-3d87-11e7-9ec3-2bc4ef303274.png)

**Comment by minida28** [comment]
I think I have found the issue.
Chrome developer tool throws this error:
```
Uncaught ReferenceError: networkcheckboxes is not defined
    at HTMLInputElement.networkSelect (config.js:383)
```
Adding this line just above line 383 on config.js file seems solve the problem:

```
var networkcheckboxes = document.getElementsByClassName("networkcheckbox");
```

**Comment by glynhudson** [comment]
Thanks, done.
