### ISSUE TITLE
Docs update and request for MQTT Client ID prefix

### ISSUE THREAD

**Issue by martynwendon** [openenergymonitor/EmonESP#27]
Hey there :-)

I just bought an emonTX and got it working with emonESP on a esp8266 huzzah.

The shop was out of stock at the time, so I had to get one elsewhere and set it up myself - I got there eventually but there's a couple of things that could do with updating in the docs to help newbies like me :-)

1) ESPAsyncTCP and ESPAsyncWebServer libraries are needed now it seems, I downloaded those as a .zip and used the library manager to add them manually as they didn't seem to come up in the library manager list.

2) It would be worth mentioning that after the sketch compile and upload the board exits bootloader mode and runs the sketch.  Trying to upload the "data" part caused a bit of head scratching as it kept failing.  I had to put the board back into bootloader mode to get the data part to upload.  Not sure if that's expected or not, but might be worth mentioning.

Finally a request if possible!  Can an MQTT Client ID **prefix** be added to the config web page and used as part of the Client ID string?  I tend to have all my MQTT stuff with Client Id prefixes as it adds an extra layer of security plus it makes it easier to scan a long list of client connections for set prefixes.

Thanks!

Martyn

**Comment by glynhudson** [comment]
Nice work getting up and running. I recomend using Platformio, its much easier than Arduino IDE to manage libs. 

Yes a reset between uploading flash and data is needed.

I'm afraid we have no plans to add MQTT client ID prefix at present. However we would not object if you wanted to have a go yourself and create a pull request.
