### ISSUE TITLE
Write apikey is not displayed on refresh of the configuration page, but is present

### ISSUE THREAD

**Issue by brucemiranda** [openenergymonitor/EmonESP#31]
Instead of the normal **** being visible in the field. The field appears blank, so you have no idea if you have entered one or not previously. 
I note that the retrieval has been commented in the code, but there needs to be another way to highlight that is was previous input.

**Comment by jeremypoulter** [comment]
Thanks, we have a fix for this in OpenEVSE and I a planning on syncing
those changes back to EmonESP in the near future.

**Comment by glynhudson** [comment]
This has now been implemented in V3.1.0
