### ISSUE TITLE
HTTPS + Not using emoncms.org + /emoncms = Doesn't work

### ISSUE THREAD

**Issue by sindudas** [openenergymonitor/EmonESP#34]
If I use https://example.com/emoncms as my EmonCMS server, I can't use HTTPS.

It's because when trying to connect to Server, uses "example.com/emomcms" has "host", and 
`client.connect(host, httpsPort)` fails.
If I put "/emoncms" at the beginning of "e_url", and leave "host" as "example.com" it works!

Maybe an input box to put the server url, will help.

**Comment by glynhudson** [comment]
I can confirm we have been able to replicate the issue. Thanks a lot for flagging this up. I'll take a look

**Comment by mabi** [comment]
I am addressing this issue in my branch [dev-issue34](/mabi/EmonESP/tree/dev-issue34) still work in progress.

**Comment by mabi** [comment]
@sindudas @glynhudson can you please build and test my branch? I don't have the hardware at hand.

**Comment by sindudas** [comment]
Flash erase , and then upload firmware and spiffs. Configured and published data through HTTPS

Good job! Thanks

**Comment by mabi** [comment]
@sindudas thank you for the test! I will update the docs with new screenshot and create a pull request, then we can close the issue

**Comment by glynhudson** [comment]
Nice work, please could you submit a PR for this. Happy to merge. Thanks a lot
