### ISSUE TITLE
MQTT no data

### ISSUE THREAD

**Issue by ArashiCZ** [openenergymonitor/EmonESP#40]
Hello,

I just installed brand new EmonTX v3 with EmonESP Huzzah.
I'm having issue with recieving data through MQTT. 
According to MQTTFX, the emonesp is connected to the server, but there is no log recieving any data at all. The base-topic is set to: emon/emonesp
MQTTFX is subscribed to: emon/emonesp/CT1
![image](https://user-images.githubusercontent.com/10303007/38386493-1d40ab50-3915-11e8-865e-69aa3795a696.png)

I'm getting values on the emonesp webserver, there are no units next to values by the way, as the
picture shows in the tutorial. It's just a small thing, but I need it there.
![image](https://user-images.githubusercontent.com/10303007/38386384-cb52c972-3914-11e8-98c7-c3674c4c9ab6.png)

Can someone help me with this?
Thanks

**Comment by glynhudson** [comment]
All setting looks correct. Are you using an emonPi?

**Comment by ArashiCZ** [comment]
Hello,

Well, I'm stupid.
I just tried lower case ct1 - ct3 and it works.
I'm using RPi3 running Node Red as Home Automation for my house.
By the way, I'm one of the guys working on the Revolution pi.

Can you look on the units next to the values?

Thanks a lot

**Comment by glynhudson** [comment]
Great!
Wow, fantastic. Revolution Pi looks like a really tidy product, nice work. 
Units can be added in Emoncms graphs.
