### ISSUE TITLE
Latest version (master) goes into bootloop on WemosD1 Mini

### ISSUE THREAD

**Issue by kerk1v** [openenergymonitor/EmonESP#50]
Hello, 

The latest version built from dev goes into a boot loop on a Wemos D1 mini. 

Version 2.3.3  works fine

Both versions will report SSIDs found on the serial console, but none will be shown in the web gui to join, I had to enter mine manually into config.cpp, after which it worked fine. 

If you need help debugging on this hardware, please let me know,

**Comment by sindudas** [comment]
May be you need to check that:

https://github.com/openenergymonitor/EmonESP#troubleshooting-upload

**Comment by kerk1v** [comment]
> May be you need to check that:
> 
> https://github.com/openenergymonitor/EmonESP#troubleshooting-upload

First thing I did, and that´s not it. As I said, 2.3.3 doesn't bootloop (but doesn't show the Wlan SSIDs either)

**Comment by sindudas** [comment]
Tried with a Wemos D1 mini the Master version, and it works. Shows all SSIDs found, select one and put the wifi password. Where did you get version 2.3.3? Latest release is 2.3.0.
