### ISSUE TITLE
Instructions to connect to EmonCMS don't explain "Node Name"

### ISSUE THREAD

**Issue by veggie2u** [openenergymonitor/EmonESP#65]
The instructions show an image of the EmonESP screen settings to connect to a EmonCMS with a Node Name of 2. There is no explanation as to what this is. Is this current? Is it supposed to be a name that matches the nodes in the EmonHub config?

**Comment by glynhudson** [comment]
No the EmonESP does not use EmonHub. The nodeName can be whatever you want the data to show up as in Emoncms e.g 'summerhouse' or 'heatpump'
