### ISSUE TITLE
Define HTTP Port of target emoncms server from UI

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonESP#89]
#42 refers

Where the target emoncms server is not running on the hardcoded port, there should be the ability to define the port to be used.

Use case is the HA Emoncms Add-on https://community.openenergymonitor.org/t/home-assistant-emoncms-addon/16524

**Comment by qm3ster** [comment]
Fixed in https://github.com/openenergymonitor/EmonESP/pull/102

**Comment by qm3ster** [comment]
#102 is not merged though?
